// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
// This file is generated by Apache Fory compiler.

package goth

import (
	"sync"
	fory "github.com/apache/fory/go/fory"
	threadsafe "github.com/apache/fory/go/fory/threadsafe"
)

type MFAType int32

const (
	MFATypeNone MFAType = 0
	MFATypeTotp MFAType = 1
	MFATypeEmailOtp MFAType = 2
)

type TokenType int32

const (
	TokenTypeAccess TokenType = 0
	TokenTypeRefresh TokenType = 1
)

type OTPPurpose int32

const (
	OTPPurposeMfa OTPPurpose = 0
	OTPPurposePasswordReset OTPPurpose = 1
	OTPPurposeEmailVerify OTPPurpose = 2
)

// Type ID 100 is specified manually.
type SignupRequest struct {
	Email string `fory:"id=1"`
	Password string `fory:"id=2"`
	FullName string `fory:"id=3"`
}

func (m *SignupRequest) ToBytes() ([]byte, error) {
	return getFory().Serialize(m)
}

func (m *SignupRequest) FromBytes(data []byte) error {
	return getFory().Deserialize(data, m)
}

// Type ID 101 is specified manually.
type SignupResponse struct {
	UserId string `fory:"id=1"`
	Email string `fory:"id=2"`
	EmailVerified bool `fory:"id=3"`
}

func (m *SignupResponse) ToBytes() ([]byte, error) {
	return getFory().Serialize(m)
}

func (m *SignupResponse) FromBytes(data []byte) error {
	return getFory().Deserialize(data, m)
}

// Type ID 102 is specified manually.
type LoginRequest struct {
	Email string `fory:"id=1"`
	Password string `fory:"id=2"`
	DeviceFingerprint string `fory:"id=3"`
}

func (m *LoginRequest) ToBytes() ([]byte, error) {
	return getFory().Serialize(m)
}

func (m *LoginRequest) FromBytes(data []byte) error {
	return getFory().Deserialize(data, m)
}

// Type ID 103 is specified manually.
type LoginResponse struct {
	AccessToken string `fory:"id=1"`
	RefreshToken string `fory:"id=2"`
	MfaRequired bool `fory:"id=3"`
	MfaSessionToken string `fory:"id=4"`
	MfaType MFAType `fory:"id=5"`
}

func (m *LoginResponse) ToBytes() ([]byte, error) {
	return getFory().Serialize(m)
}

func (m *LoginResponse) FromBytes(data []byte) error {
	return getFory().Deserialize(data, m)
}

// Type ID 104 is specified manually.
type LogoutRequest struct {
	RefreshToken string `fory:"id=1"`
}

func (m *LogoutRequest) ToBytes() ([]byte, error) {
	return getFory().Serialize(m)
}

func (m *LogoutRequest) FromBytes(data []byte) error {
	return getFory().Deserialize(data, m)
}

// Type ID 105 is specified manually.
type LogoutResponse struct {
	Success bool `fory:"id=1"`
}

func (m *LogoutResponse) ToBytes() ([]byte, error) {
	return getFory().Serialize(m)
}

func (m *LogoutResponse) FromBytes(data []byte) error {
	return getFory().Deserialize(data, m)
}

// Type ID 106 is specified manually.
type RefreshTokenRequest struct {
	RefreshToken string `fory:"id=1"`
}

func (m *RefreshTokenRequest) ToBytes() ([]byte, error) {
	return getFory().Serialize(m)
}

func (m *RefreshTokenRequest) FromBytes(data []byte) error {
	return getFory().Deserialize(data, m)
}

// Type ID 107 is specified manually.
type RefreshTokenResponse struct {
	AccessToken string `fory:"id=1"`
	RefreshToken string `fory:"id=2"`
}

func (m *RefreshTokenResponse) ToBytes() ([]byte, error) {
	return getFory().Serialize(m)
}

func (m *RefreshTokenResponse) FromBytes(data []byte) error {
	return getFory().Deserialize(data, m)
}

// Type ID 108 is specified manually.
type EnableMFARequest struct {
	MfaType MFAType `fory:"id=1"`
}

func (m *EnableMFARequest) ToBytes() ([]byte, error) {
	return getFory().Serialize(m)
}

func (m *EnableMFARequest) FromBytes(data []byte) error {
	return getFory().Deserialize(data, m)
}

// Type ID 109 is specified manually.
type EnableMFAResponse struct {
	Success bool `fory:"id=1"`
	TotpSecret string `fory:"id=2"`
	TotpQrUrl string `fory:"id=3"`
	OtpExpiresIn int32 `fory:"id=4"`
}

func (m *EnableMFAResponse) ToBytes() ([]byte, error) {
	return getFory().Serialize(m)
}

func (m *EnableMFAResponse) FromBytes(data []byte) error {
	return getFory().Deserialize(data, m)
}

// Type ID 110 is specified manually.
type VerifyMFARequest struct {
	MfaSessionToken string `fory:"id=1"`
	Code string `fory:"id=2"`
}

func (m *VerifyMFARequest) ToBytes() ([]byte, error) {
	return getFory().Serialize(m)
}

func (m *VerifyMFARequest) FromBytes(data []byte) error {
	return getFory().Deserialize(data, m)
}

// Type ID 111 is specified manually.
type VerifyMFAResponse struct {
	AccessToken string `fory:"id=1"`
	RefreshToken string `fory:"id=2"`
	Success bool `fory:"id=3"`
}

func (m *VerifyMFAResponse) ToBytes() ([]byte, error) {
	return getFory().Serialize(m)
}

func (m *VerifyMFAResponse) FromBytes(data []byte) error {
	return getFory().Deserialize(data, m)
}

// Type ID 112 is specified manually.
type DisableMFARequest struct {
	Code string `fory:"id=1"`
}

func (m *DisableMFARequest) ToBytes() ([]byte, error) {
	return getFory().Serialize(m)
}

func (m *DisableMFARequest) FromBytes(data []byte) error {
	return getFory().Deserialize(data, m)
}

// Type ID 113 is specified manually.
type DisableMFAResponse struct {
	Success bool `fory:"id=1"`
}

func (m *DisableMFAResponse) ToBytes() ([]byte, error) {
	return getFory().Serialize(m)
}

func (m *DisableMFAResponse) FromBytes(data []byte) error {
	return getFory().Deserialize(data, m)
}

// Type ID 114 is specified manually.
type SendOTPRequest struct {
	Email string `fory:"id=1"`
	Purpose OTPPurpose `fory:"id=2"`
}

func (m *SendOTPRequest) ToBytes() ([]byte, error) {
	return getFory().Serialize(m)
}

func (m *SendOTPRequest) FromBytes(data []byte) error {
	return getFory().Deserialize(data, m)
}

// Type ID 115 is specified manually.
type SendOTPResponse struct {
	Success bool `fory:"id=1"`
	ExpiresInSeconds int32 `fory:"id=2"`
}

func (m *SendOTPResponse) ToBytes() ([]byte, error) {
	return getFory().Serialize(m)
}

func (m *SendOTPResponse) FromBytes(data []byte) error {
	return getFory().Deserialize(data, m)
}

// Type ID 116 is specified manually.
type VerifyOTPRequest struct {
	Email string `fory:"id=1"`
	Code string `fory:"id=2"`
	Purpose OTPPurpose `fory:"id=3"`
}

func (m *VerifyOTPRequest) ToBytes() ([]byte, error) {
	return getFory().Serialize(m)
}

func (m *VerifyOTPRequest) FromBytes(data []byte) error {
	return getFory().Deserialize(data, m)
}

// Type ID 117 is specified manually.
type VerifyOTPResponse struct {
	Success bool `fory:"id=1"`
	SessionToken string `fory:"id=2"`
}

func (m *VerifyOTPResponse) ToBytes() ([]byte, error) {
	return getFory().Serialize(m)
}

func (m *VerifyOTPResponse) FromBytes(data []byte) error {
	return getFory().Deserialize(data, m)
}

// Type ID 118 is specified manually.
type ValidateTokenRequest struct {
	AccessToken string `fory:"id=1"`
}

func (m *ValidateTokenRequest) ToBytes() ([]byte, error) {
	return getFory().Serialize(m)
}

func (m *ValidateTokenRequest) FromBytes(data []byte) error {
	return getFory().Deserialize(data, m)
}

// Type ID 119 is specified manually.
type ValidateTokenResponse struct {
	Valid bool `fory:"id=1"`
	UserId string `fory:"id=2"`
	Email string `fory:"id=3"`
	MfaVerified bool `fory:"id=4"`
}

func (m *ValidateTokenResponse) ToBytes() ([]byte, error) {
	return getFory().Serialize(m)
}

func (m *ValidateTokenResponse) FromBytes(data []byte) error {
	return getFory().Deserialize(data, m)
}

// Type ID 120 is specified manually.
type GetUserRequest struct {
	UserId string `fory:"id=1"`
}

func (m *GetUserRequest) ToBytes() ([]byte, error) {
	return getFory().Serialize(m)
}

func (m *GetUserRequest) FromBytes(data []byte) error {
	return getFory().Deserialize(data, m)
}

// Type ID 121 is specified manually.
type GetUserResponse struct {
	UserId string `fory:"id=1"`
	Email string `fory:"id=2"`
	FullName string `fory:"id=3"`
	EmailVerified bool `fory:"id=4"`
	MfaType MFAType `fory:"id=5"`
	CreatedAt int64 `fory:"id=6"`
}

func (m *GetUserResponse) ToBytes() ([]byte, error) {
	return getFory().Serialize(m)
}

func (m *GetUserResponse) FromBytes(data []byte) error {
	return getFory().Deserialize(data, m)
}

// Type ID 122 is specified manually.
type UpdatePasswordRequest struct {
	UserId string `fory:"id=1"`
	OldPassword string `fory:"id=2"`
	NewPassword string `fory:"id=3"`
}

func (m *UpdatePasswordRequest) ToBytes() ([]byte, error) {
	return getFory().Serialize(m)
}

func (m *UpdatePasswordRequest) FromBytes(data []byte) error {
	return getFory().Deserialize(data, m)
}

// Type ID 123 is specified manually.
type UpdatePasswordResponse struct {
	Success bool `fory:"id=1"`
}

func (m *UpdatePasswordResponse) ToBytes() ([]byte, error) {
	return getFory().Serialize(m)
}

func (m *UpdatePasswordResponse) FromBytes(data []byte) error {
	return getFory().Deserialize(data, m)
}

func RegisterTypes(f *fory.Fory) error {
	if err := f.RegisterEnum(MFAType(0), 107685052); err != nil {
		return err
	}
	if err := f.RegisterEnum(TokenType(0), 4259159742); err != nil {
		return err
	}
	if err := f.RegisterEnum(OTPPurpose(0), 299433278); err != nil {
		return err
	}
	if err := f.RegisterStruct(SignupRequest{}, 100); err != nil {
		return err
	}
	if err := f.RegisterStruct(SignupResponse{}, 101); err != nil {
		return err
	}
	if err := f.RegisterStruct(LoginRequest{}, 102); err != nil {
		return err
	}
	if err := f.RegisterStruct(LoginResponse{}, 103); err != nil {
		return err
	}
	if err := f.RegisterStruct(LogoutRequest{}, 104); err != nil {
		return err
	}
	if err := f.RegisterStruct(LogoutResponse{}, 105); err != nil {
		return err
	}
	if err := f.RegisterStruct(RefreshTokenRequest{}, 106); err != nil {
		return err
	}
	if err := f.RegisterStruct(RefreshTokenResponse{}, 107); err != nil {
		return err
	}
	if err := f.RegisterStruct(EnableMFARequest{}, 108); err != nil {
		return err
	}
	if err := f.RegisterStruct(EnableMFAResponse{}, 109); err != nil {
		return err
	}
	if err := f.RegisterStruct(VerifyMFARequest{}, 110); err != nil {
		return err
	}
	if err := f.RegisterStruct(VerifyMFAResponse{}, 111); err != nil {
		return err
	}
	if err := f.RegisterStruct(DisableMFARequest{}, 112); err != nil {
		return err
	}
	if err := f.RegisterStruct(DisableMFAResponse{}, 113); err != nil {
		return err
	}
	if err := f.RegisterStruct(SendOTPRequest{}, 114); err != nil {
		return err
	}
	if err := f.RegisterStruct(SendOTPResponse{}, 115); err != nil {
		return err
	}
	if err := f.RegisterStruct(VerifyOTPRequest{}, 116); err != nil {
		return err
	}
	if err := f.RegisterStruct(VerifyOTPResponse{}, 117); err != nil {
		return err
	}
	if err := f.RegisterStruct(ValidateTokenRequest{}, 118); err != nil {
		return err
	}
	if err := f.RegisterStruct(ValidateTokenResponse{}, 119); err != nil {
		return err
	}
	if err := f.RegisterStruct(GetUserRequest{}, 120); err != nil {
		return err
	}
	if err := f.RegisterStruct(GetUserResponse{}, 121); err != nil {
		return err
	}
	if err := f.RegisterStruct(UpdatePasswordRequest{}, 122); err != nil {
		return err
	}
	if err := f.RegisterStruct(UpdatePasswordResponse{}, 123); err != nil {
		return err
	}
	return nil
}

func createFory() *fory.Fory {
	f := fory.New(fory.WithXlang(true), fory.WithRefTracking(true), fory.WithCompatible(true))
	if err := RegisterTypes(f); err != nil {
		panic(err)
	}
	return f
}

var (
	foryOnce sync.Once
	foryInstance *threadsafe.Fory
)

func getFory() *threadsafe.Fory {
	foryOnce.Do(func() {
		foryInstance = threadsafe.NewWithFactory(createFory)
	})
	return foryInstance
}
