// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
// This file is generated by Apache Fory compiler.

package goth

import (
	"context"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/mem"
	"google.golang.org/grpc/status"
)

// CodecV2 implements grpc/encoding.CodecV2 using Fory serialization.
// It uses the generated package-level thread-safe Fory runtime.
type CodecV2 struct{}

// Marshal serializes v with Fory. The generated thread-safe runtime returns
// a stable copy before releasing pooled Fory instances, so gRPC never sees
// the reusable internal buffers owned by plain fory.Fory runtimes.
func (c CodecV2) Marshal(v any) (mem.BufferSlice, error) {
	b, err := getFory().Serialize(v)
	if err != nil {
		return nil, err
	}
	return mem.BufferSlice{mem.NewBuffer(&b, nil)}, nil
}

// Unmarshal deserializes the gRPC frame into v. Each buffer segment is
// copied into a fresh slice because the transport may reclaim the
// underlying memory before Fory finishes reading it.
func (c CodecV2) Unmarshal(data mem.BufferSlice, v any) error {
	b := make([]byte, data.Len())
	n := 0
	for _, buf := range data {
		n += copy(b[n:], buf.ReadOnlyData())
	}
	return getFory().Deserialize(b, v)
}

// Name returns "fory", the codec identifier used with grpc.ForceCodecV2.
func (CodecV2) Name() string { return "fory" }

// GothServiceClient is the client API for GothService service.
type GothServiceClient interface {
	Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	EnableMFA(ctx context.Context, in *EnableMFARequest, opts ...grpc.CallOption) (*EnableMFAResponse, error)
	VerifyMFA(ctx context.Context, in *VerifyMFARequest, opts ...grpc.CallOption) (*VerifyMFAResponse, error)
	DisableMFA(ctx context.Context, in *DisableMFARequest, opts ...grpc.CallOption) (*DisableMFAResponse, error)
	SendOTP(ctx context.Context, in *SendOTPRequest, opts ...grpc.CallOption) (*SendOTPResponse, error)
	VerifyOTP(ctx context.Context, in *VerifyOTPRequest, opts ...grpc.CallOption) (*VerifyOTPResponse, error)
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*UpdatePasswordResponse, error)
}

type gothServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGothServiceClient(cc grpc.ClientConnInterface) GothServiceClient {
	return &gothServiceClient{cc: cc}
}

func (c *gothServiceClient) Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error) {
	out := new(SignupResponse)
	callOpts := append([]grpc.CallOption{grpc.ForceCodecV2(CodecV2{})}, opts...)
	err := c.cc.Invoke(ctx, "/goth.GothService/Signup", in, out, callOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gothServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	callOpts := append([]grpc.CallOption{grpc.ForceCodecV2(CodecV2{})}, opts...)
	err := c.cc.Invoke(ctx, "/goth.GothService/Login", in, out, callOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gothServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	callOpts := append([]grpc.CallOption{grpc.ForceCodecV2(CodecV2{})}, opts...)
	err := c.cc.Invoke(ctx, "/goth.GothService/Logout", in, out, callOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gothServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	out := new(RefreshTokenResponse)
	callOpts := append([]grpc.CallOption{grpc.ForceCodecV2(CodecV2{})}, opts...)
	err := c.cc.Invoke(ctx, "/goth.GothService/RefreshToken", in, out, callOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gothServiceClient) EnableMFA(ctx context.Context, in *EnableMFARequest, opts ...grpc.CallOption) (*EnableMFAResponse, error) {
	out := new(EnableMFAResponse)
	callOpts := append([]grpc.CallOption{grpc.ForceCodecV2(CodecV2{})}, opts...)
	err := c.cc.Invoke(ctx, "/goth.GothService/EnableMFA", in, out, callOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gothServiceClient) VerifyMFA(ctx context.Context, in *VerifyMFARequest, opts ...grpc.CallOption) (*VerifyMFAResponse, error) {
	out := new(VerifyMFAResponse)
	callOpts := append([]grpc.CallOption{grpc.ForceCodecV2(CodecV2{})}, opts...)
	err := c.cc.Invoke(ctx, "/goth.GothService/VerifyMFA", in, out, callOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gothServiceClient) DisableMFA(ctx context.Context, in *DisableMFARequest, opts ...grpc.CallOption) (*DisableMFAResponse, error) {
	out := new(DisableMFAResponse)
	callOpts := append([]grpc.CallOption{grpc.ForceCodecV2(CodecV2{})}, opts...)
	err := c.cc.Invoke(ctx, "/goth.GothService/DisableMFA", in, out, callOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gothServiceClient) SendOTP(ctx context.Context, in *SendOTPRequest, opts ...grpc.CallOption) (*SendOTPResponse, error) {
	out := new(SendOTPResponse)
	callOpts := append([]grpc.CallOption{grpc.ForceCodecV2(CodecV2{})}, opts...)
	err := c.cc.Invoke(ctx, "/goth.GothService/SendOTP", in, out, callOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gothServiceClient) VerifyOTP(ctx context.Context, in *VerifyOTPRequest, opts ...grpc.CallOption) (*VerifyOTPResponse, error) {
	out := new(VerifyOTPResponse)
	callOpts := append([]grpc.CallOption{grpc.ForceCodecV2(CodecV2{})}, opts...)
	err := c.cc.Invoke(ctx, "/goth.GothService/VerifyOTP", in, out, callOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gothServiceClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	out := new(ValidateTokenResponse)
	callOpts := append([]grpc.CallOption{grpc.ForceCodecV2(CodecV2{})}, opts...)
	err := c.cc.Invoke(ctx, "/goth.GothService/ValidateToken", in, out, callOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gothServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	callOpts := append([]grpc.CallOption{grpc.ForceCodecV2(CodecV2{})}, opts...)
	err := c.cc.Invoke(ctx, "/goth.GothService/GetUser", in, out, callOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gothServiceClient) UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*UpdatePasswordResponse, error) {
	out := new(UpdatePasswordResponse)
	callOpts := append([]grpc.CallOption{grpc.ForceCodecV2(CodecV2{})}, opts...)
	err := c.cc.Invoke(ctx, "/goth.GothService/UpdatePassword", in, out, callOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GothServiceServer is the server API for GothService service.
// All implementations must embed UnimplementedGothServiceServer
// for forward compatibility.
type GothServiceServer interface {
	Signup(context.Context, *SignupRequest) (*SignupResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	EnableMFA(context.Context, *EnableMFARequest) (*EnableMFAResponse, error)
	VerifyMFA(context.Context, *VerifyMFARequest) (*VerifyMFAResponse, error)
	DisableMFA(context.Context, *DisableMFARequest) (*DisableMFAResponse, error)
	SendOTP(context.Context, *SendOTPRequest) (*SendOTPResponse, error)
	VerifyOTP(context.Context, *VerifyOTPRequest) (*VerifyOTPResponse, error)
	ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	UpdatePassword(context.Context, *UpdatePasswordRequest) (*UpdatePasswordResponse, error)
	mustEmbedUnimplementedGothServiceServer()
}

// UnimplementedGothServiceServer must be embedded to have forward compatible implementation.
type UnimplementedGothServiceServer struct {}

func (UnimplementedGothServiceServer) mustEmbedUnimplementedGothServiceServer() {}

func (UnimplementedGothServiceServer) Signup(context.Context, *SignupRequest) (*SignupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}

func (UnimplementedGothServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}

func (UnimplementedGothServiceServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}

func (UnimplementedGothServiceServer) RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}

func (UnimplementedGothServiceServer) EnableMFA(context.Context, *EnableMFARequest) (*EnableMFAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableMFA not implemented")
}

func (UnimplementedGothServiceServer) VerifyMFA(context.Context, *VerifyMFARequest) (*VerifyMFAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyMFA not implemented")
}

func (UnimplementedGothServiceServer) DisableMFA(context.Context, *DisableMFARequest) (*DisableMFAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableMFA not implemented")
}

func (UnimplementedGothServiceServer) SendOTP(context.Context, *SendOTPRequest) (*SendOTPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendOTP not implemented")
}

func (UnimplementedGothServiceServer) VerifyOTP(context.Context, *VerifyOTPRequest) (*VerifyOTPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyOTP not implemented")
}

func (UnimplementedGothServiceServer) ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}

func (UnimplementedGothServiceServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}

func (UnimplementedGothServiceServer) UpdatePassword(context.Context, *UpdatePasswordRequest) (*UpdatePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePassword not implemented")
}

func _GothService_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GothServiceServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:	srv,
		FullMethod:	"/goth.GothService/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GothServiceServer).Signup(ctx, req.(*SignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GothService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GothServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:	srv,
		FullMethod:	"/goth.GothService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GothServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GothService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GothServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:	srv,
		FullMethod:	"/goth.GothService/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GothServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GothService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GothServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:	srv,
		FullMethod:	"/goth.GothService/RefreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GothServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GothService_EnableMFA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableMFARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GothServiceServer).EnableMFA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:	srv,
		FullMethod:	"/goth.GothService/EnableMFA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GothServiceServer).EnableMFA(ctx, req.(*EnableMFARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GothService_VerifyMFA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyMFARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GothServiceServer).VerifyMFA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:	srv,
		FullMethod:	"/goth.GothService/VerifyMFA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GothServiceServer).VerifyMFA(ctx, req.(*VerifyMFARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GothService_DisableMFA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableMFARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GothServiceServer).DisableMFA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:	srv,
		FullMethod:	"/goth.GothService/DisableMFA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GothServiceServer).DisableMFA(ctx, req.(*DisableMFARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GothService_SendOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GothServiceServer).SendOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:	srv,
		FullMethod:	"/goth.GothService/SendOTP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GothServiceServer).SendOTP(ctx, req.(*SendOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GothService_VerifyOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GothServiceServer).VerifyOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:	srv,
		FullMethod:	"/goth.GothService/VerifyOTP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GothServiceServer).VerifyOTP(ctx, req.(*VerifyOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GothService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GothServiceServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:	srv,
		FullMethod:	"/goth.GothService/ValidateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GothServiceServer).ValidateToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GothService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GothServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:	srv,
		FullMethod:	"/goth.GothService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GothServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GothService_UpdatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GothServiceServer).UpdatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:	srv,
		FullMethod:	"/goth.GothService/UpdatePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GothServiceServer).UpdatePassword(ctx, req.(*UpdatePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GothService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "goth.GothService",
	HandlerType: (*GothServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName:	"Signup",
			Handler:	_GothService_Signup_Handler,
		},
		{
			MethodName:	"Login",
			Handler:	_GothService_Login_Handler,
		},
		{
			MethodName:	"Logout",
			Handler:	_GothService_Logout_Handler,
		},
		{
			MethodName:	"RefreshToken",
			Handler:	_GothService_RefreshToken_Handler,
		},
		{
			MethodName:	"EnableMFA",
			Handler:	_GothService_EnableMFA_Handler,
		},
		{
			MethodName:	"VerifyMFA",
			Handler:	_GothService_VerifyMFA_Handler,
		},
		{
			MethodName:	"DisableMFA",
			Handler:	_GothService_DisableMFA_Handler,
		},
		{
			MethodName:	"SendOTP",
			Handler:	_GothService_SendOTP_Handler,
		},
		{
			MethodName:	"VerifyOTP",
			Handler:	_GothService_VerifyOTP_Handler,
		},
		{
			MethodName:	"ValidateToken",
			Handler:	_GothService_ValidateToken_Handler,
		},
		{
			MethodName:	"GetUser",
			Handler:	_GothService_GetUser_Handler,
		},
		{
			MethodName:	"UpdatePassword",
			Handler:	_GothService_UpdatePassword_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
	},
	Metadata: "goth.fdl",
}

func RegisterGothServiceServer(s grpc.ServiceRegistrar, srv GothServiceServer) {
	s.RegisterService(&_GothService_serviceDesc, srv)
}
