syntax = "proto3";
package auth;
option go_package = "github.com/ayush00git/goth/proto";

message User {
  string id         = 1;
  string user_name  = 2;
  string email      = 3;
  string role       = 4;
  bool   is_verified = 5;
  string created_at = 6;
}

message SignupRequest  { string user_name = 1; string email = 2; string password = 3; }
message SignupResponse { string message = 1; User user = 2; }

message LoginRequest   { string email = 1; string password = 2; }
message LoginResponse  { string message = 1; string token = 2; }

message LogoutRequest  {}
message LogoutResponse { string message = 1; }

message VerifyEmailRequest  { string token = 1; }
message VerifyEmailResponse { string message = 1; }

message GetUsersRequest  {}
message GetUsersResponse { string message = 1; string requested_by = 2; repeated User users = 3; }

// --- for streaming stages ---
message WatchSessionsRequest { string user_id = 1; }
message SessionEvent {
  string event_type = 1;   // "login", "logout", "expired"
  string session_id = 2;
  string ip_address = 3;
  string occurred_at = 4;
}

message RevokeTokenRequest  { string token = 1; }
message RevokeTokenResponse { int32 revoked_count = 1; }

message AuditRequest { string action = 1; string payload = 2; }
message AuditEvent   { string description = 1; string timestamp = 2; }

service AuthService {
  // unary
  rpc Signup      (SignupRequest)      returns (SignupResponse);
  rpc Login       (LoginRequest)       returns (LoginResponse);
  rpc Logout      (LogoutRequest)      returns (LogoutResponse);
  rpc VerifyEmail (VerifyEmailRequest) returns (VerifyEmailResponse);
  rpc GetUsers    (GetUsersRequest)    returns (GetUsersResponse);

  // server streaming — server pushes session events to client
  rpc WatchSessions (WatchSessionsRequest) returns (stream SessionEvent);

  // client streaming — client sends many tokens, server revokes all
  rpc BulkRevokeTokens (stream RevokeTokenRequest) returns (RevokeTokenResponse);

  // bidirectional streaming — live audit log conversation
  rpc AuditStream (stream AuditRequest) returns (stream AuditEvent);
}